# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('complete', models.FloatField(blank=True, default=0.0)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('budget', models.IntegerField(blank=True, default=0)),
                ('report', models.CharField(blank=True, max_length=500)),
                ('accepted', models.NullBooleanField()),
                ('datetimeaccept', models.DateTimeField(blank=True, null=True)),
                ('assigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_budget', models.IntegerField(default=0)),
                ('assigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=500)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AssignedKPI')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('0', 'Направление'), ('1', 'Кафедра'), ('2', 'Научная группа'), ('3', 'Лаборатория')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.Department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='KPI',
            field=models.ManyToManyField(through='app.AssignedKPI', to='app.KPI'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superior_of_this_department', to='app.Department'),
        ),
        migrations.AddField(
            model_name='comments',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='app.UserProfile'),
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Department'),
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department'),
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.KPI', verbose_name='KPI'),
        ),
    ]
