# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedkpi',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='assigned_budget',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
