# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160714_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.ForeignKey(default=datetime.datetime(2016, 7, 14, 22, 38, 21, 627357, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app.Type'),
            preserve_default=False,
        ),
    ]
