# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160725_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedkpi',
            name='budget',
            field=models.IntegerField(blank=True, default=0, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='complete',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='report',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
    ]
