# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160725_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedkpi',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='complete',
            field=models.IntegerField(blank=True, default=0, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('0', 'Ректорат'), ('1', 'Направление'), ('2', 'Кафедра'), ('3', 'Научная группа'), ('4', 'Лаборатория')], max_length=1),
        ),
    ]
