# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160715_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='app.UserProfile'),
        ),
    ]
