# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160726_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedkpi',
            name='budget',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='complete',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='report',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comments',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name=''),
        ),
    ]
