# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:22
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160727_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedkpi',
            name='amount',
            field=models.IntegerField(default=0, validators=[app.validators.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='assigned_budget',
            field=models.IntegerField(default=0, validators=[app.validators.validate_non_negative], verbose_name='Количество'),
        ),
    ]
