# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160715_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedkpi',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
