# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assignedkpi_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.AssignedKPI'),
        ),
        migrations.AddField(
            model_name='comments',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='app.UserProfile'),
        ),
    ]
