# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160726_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedkpi',
            name='complete',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
