# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160717_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='subordinate',
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('0', 'Направление'), ('1', 'Кафедра'), ('2', 'Научная группа'), ('3', 'Лаборатория')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
