# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_assignedkpi_assigner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(blank=True)),
                ('assigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='budget',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Budget'),
        ),
    ]
