# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160721_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='datetime',
        ),
    ]
