# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_budget_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
