# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_budget_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptRejectKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='budget',
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='report',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Department'),
        ),
        migrations.AddField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptrejectkpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AssignedKPI'),
        ),
    ]
