# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160721_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptrejectkpi',
            name='accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
