# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160721_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='accept_reject',
        ),
        migrations.RemoveField(
            model_name='position',
            name='report',
        ),
        migrations.RemoveField(
            model_name='position',
            name='spread_KPI',
        ),
        migrations.RemoveField(
            model_name='position',
            name='spread_budget',
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='budget',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='complete',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
