# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160722_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='accept_reject',
        ),
        migrations.RemoveField(
            model_name='position',
            name='report',
        ),
        migrations.RemoveField(
            model_name='position',
            name='spread_KPI',
        ),
        migrations.RemoveField(
            model_name='position',
            name='spread_budget',
        ),
    ]
