# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160722_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.Department'),
        ),
    ]
