# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160722_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedkpi',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='complete',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
