# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160723_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptrejectkpi',
            name='kpi',
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='assignedkpi',
            name='datetimeaccept',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AcceptRejectKPI',
        ),
    ]
