# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160723_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedkpi',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.KPI', verbose_name='KPI'),
        ),
    ]
