# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160724_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedkpi',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('0', 'Ректорат'), ('1', 'Направление'), ('2', 'Кафедра'), ('3', 'Научная группа'), ('4', 'Лаборатория')], max_length=1),
        ),
    ]
