# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160724_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedkpi',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 25, 11, 47, 19, 448667, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
