# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160725_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignedkpi',
            name='complete',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
