# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160725_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedkpi',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
