# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20160725_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name=''),
        ),
    ]
