# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20160725_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedkpi',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
    ]
